apiVersion: v1
kind: Service
metadata:
  name: ftptest-service
  namespace: ns3
spec:
  type: LoadBalancer
  selector:
    app: ftptest
  ports:
  - port: 21
    nodePort: 30083
    name: port1
  - port: 31200
    nodePort: 31400
    name: port2
  - port: 31201
    nodePort: 31401
    name: port3
  - port: 31202
    nodePort: 31402
    name: port4
  - port: 31203
    nodePort: 31403
    name: port5
