apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftptest-pvc2
  namespace: ns2
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 4Gi
