apiVersion: v1
kind: Service
metadata:
  name: ftptest-service
  namespace: ns2
spec:
  type: LoadBalancer
  selector:
    app: ftptest
  ports:
  - port: 21
    nodePort: 30082
    name: port1
  - port: 31200
    nodePort: 31300
    name: port2
  - port: 31201
    nodePort: 31301
    name: port3
  - port: 31202
    nodePort: 31302
    name: port4
  - port: 31303
    nodePort: 31303
    name: port5
