apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftptest-pvc
  namespace: ns1
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver
  resources:
    requests:
      storage: 1Gi
